baseURL = 'https://jamiesecops.github.io/'
languageCode = 'en-us'
title = '2-Minute Intel'

copyright = "© jamieSecOps"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=false
	subtitle = "Bite-sized Cyber Threat Intelligence"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/jamieSecOps"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/jamie-khan-b751147/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4